# A docker file to run a next.js project

# Use the official node image
# https://hub.docker.com/_/node
FROM node:12

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying them separately prevents re-running yarn install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN yarn install

# Copy local code to the container image.
COPY . .

# Run the web service on container startup.
CMD [ "yarn", "run", "dev" ]