version: '3.8'

services:
  client:
    build: ./dockerfile
    ports:
      - 3000:3020
    volumes:
      - type: volume
          source: ./
          target: /data
          volume:
            nocopy: true
